#ifndef RADIX_SORT_COMMON_GLSL
#define RADIX_SORT_COMMON_GLSL

#define RADIX_PASS_COUNT 4
#define RADIX_BIT_COUNT 8
#define RADIX_HISTOGRAM_SIZE (1U << RADIX_BIT_COUNT)
#define THREAD_TILE_SIZE 1
#define COUNT_WORKGROUP_SIZE 512
#define COUNT_TILE_SIZE (COUNT_WORKGROUP_SIZE * THREAD_TILE_SIZE)
#define SCAN_WORKGROUP_SIZE (COUNT_WORKGROUP_SIZE / 2)

#endif /* RADIX_SORT_COMMON_GLSL */
